database:
    # the name of the JDBC driver, mysql in our case
    driverClass: "org.h2.Driver"
    # the username
    user: ""
    # the password
    password: ""
    # the JDBC URL; the database is called DWGettingStarted
    url: "jdbc:h2:~/flywaytestdb"
    properties:
            hibernate.dialect: org.hibernate.dialect.H2Dialect
            hibernate.hbm2ddl.auto: create

